### ISSUE TITLE
Does get ico of exe by parse pe using js?

### ISSUE THREAD

**Issue by L1yp** [jirsh/pe-parser#5]
in browser?

**Comment by jirsh** [comment]
Hello sir, thanks for opening this issue. It does not actually have capability of parsing resources. Also when it comes to browser support all I can say is try it. I personally don't think it works because of the use of the Buffer class which I'm pretty sure is node js if not then it should work. I've only tested and use it with backend projects!

**Comment by jirsh** [comment]
I found this actually https://stackoverflow.com/a/16548689 , should help if you decide to implement it browser based

**Comment by L1yp** [comment]
> I found this actually https://stackoverflow.com/a/16548689 , should help if you decide to implement it browser based

Thank you. I'm sorry to see it now. I haven't read my email for several days.
